### ISSUE TITLE
Keyboard disappears when editing screenshot text

### ISSUE THREAD

**Issue by smartinrub** [mpdifran/picasso-roadmap#27]
**Info:**
 Device: [e.g. iPhone 15 Pro]
 OS: [e.g. iOS 17.0.2]
 Picasso Version [e.g. 1.0]

**Describe the bug**
When editing text on a screenshot the keyboard and options disappear as soon as you type anything or select some of the options.

**Screenshots**

![image](https://github.com/mpdifran/picasso-roadmap/assets/26189335/d202b861-49b0-4026-a50a-3293021574d0)

![image](https://github.com/mpdifran/picasso-roadmap/assets/26189335/fa00db0e-e542-4607-88f2-5be0508ba3bc)

**Comment by mpdifran** [comment]
Wow super weird. I was able to reproduce it once, it's likely related to the document auto-saving.

I'm planning on spending some time making text editing easier, so hopefully that helps fix this.

Thanks for logging it!

**Comment by mpdifran** [comment]
I found the issue! Luckily the fix was easy, a patch is coming soon, likely tomorrow.

**Comment by smartinrub** [comment]
> I found the issue! Luckily the fix was easy, a patch is coming soon, likely tomorrow.

Great, thanks!
