### ISSUE TITLE
Add feature to easily localize screenshot

### ISSUE THREAD

**Issue by lchamp** [mpdifran/picasso-roadmap#36]
Making AppStore screenshot is always tiresome, especially when we need to make for several device **and multiply for each languages**.

Would it be possible to use something like localizable, stringdict or something else to work with translation in an easier way?

**Comment by mpdifran** [comment]
💯

This is one of the big things I'd love to bring to Picasso. Also auto uploading to the App Store haha.

**Comment by mpdifran** [comment]
Closing this out since Picasso now supports localization!
