### ISSUE TITLE
Allow to use gradient for background

### ISSUE THREAD

**Issue by lchamp** [mpdifran/picasso-roadmap#37]
It would be nice if we could select `gradient` as a type of background.
Instead of choosing only one `solid color` we could choose here:

- color one
- color two
- angle

**Comment by lchamp** [comment]
Neverming I didn't saw other features that are already for 1.1
https://github.com/mpdifran/picasso-roadmap/milestone/2

We can probably close this one then.

**Comment by mpdifran** [comment]
Yes! This will be available very soon (plus other goodies).
