### ISSUE TITLE
Allow for screenshots from devices with "Display Zoom" set to "Large Text"

### ISSUE THREAD

**Issue by DimitarNestorov** [mpdifran/picasso-roadmap#39]
**Info:**
 Device: iPhone 12
 OS: macOS 14.0
 Picasso Version 1.0.3

**Describe the bug**

When I have "Display Zoom" set to "Large Text" (Settings -> Display & Brightness -> Display Zoom) the screen resolution is lower and I can't use those screenshots

**Expected behavior**
No error

**Screenshots**
<img width="369" alt="image" src="https://github.com/mpdifran/picasso-roadmap/assets/8790386/6e677b13-ee11-41c4-b1ea-817c59f08ccd">

**Comment by mpdifran** [comment]
Ooh good catch, I'll definitely schedule this ASAP.

**Comment by mpdifran** [comment]
Taking a look at this now, what device screenshot were you trying to frame? 

It looks like there's no easy way to determine the screenshot resolution for every device via the simulator. I've added the proper sizes for my phone (iPhone 15 Pro), but just wanted to make sure I cover your device as well.

**Comment by mpdifran** [comment]
Ok I've added the dimension in the screenshot for iPhone 12 and iPhone 12 Pro, hopefully it aligns properly. I'll keep looking into whether I can get the official scaled screen dimensions for all devices.

**Comment by mpdifran** [comment]
Ah that's a good call! I did find a resource that had all the dimensions, so we should be good here for all devices.

**Comment by mpdifran** [comment]
Yup! Here it is: https://www.screensizes.app
