### ISSUE TITLE
Duplicate only one Screenshot to other group

### ISSUE THREAD

**Issue by TimoWinkelmann** [mpdifran/picasso-roadmap#48]
I miss the function to duplicate only a single screenshot into the other groups. 
If I now add a screenshot later and then want to add it in the other groups by duplicating, I will also overwrite all other screens.

**Comment by mpdifran** [comment]
I've had the same problem as well! I can definitely add this!

**Comment by TimoWinkelmann** [comment]
Thank you.

I also have a few more ideas.

If you need beta testers, let me know.

**Comment by mpdifran** [comment]
Sure! Send an email to getpicasso@gmail.com and I'll get that set up.
