### ISSUE TITLE
MacOS Screenshots

### ISSUE THREAD

**Issue by Mcrich23** [mpdifran/picasso-roadmap#49]
**Info:**
 Device: M1 Pro MBP 14"
 OS: 14.4
 Picasso Version 1.2

**Describe the bug**
Macos screenshots are not allowed. States screenshot dimensions are not a recognized screen size

**Expected behavior**
Macos screenshots are allows

**Screenshots**

<img width="1512" alt="Screenshot 2024-02-07 at 3 27 28 PM" src="https://github.com/mpdifran/picasso-roadmap/assets/81453549/d3e3ca10-06d0-4d9b-9a11-e04e8bdcc88a">
<img width="1512" alt="Screenshot 2024-02-07 at 3 27 50 PM" src="https://github.com/mpdifran/picasso-roadmap/assets/81453549/bc056f8c-24b2-4c56-b6bf-b4df69b24847">

**Comment by Mcrich23** [comment]
Maybe understanding the device frame sizes will help

**Comment by mpdifran** [comment]
Thanks for the feedback! Yeah I agree, I can add some more documentation around this for sure.

**Comment by mpdifran** [comment]
I've added supported resolutions in the placeholder, so hopefully this helps in the future!
