### ISSUE TITLE
Several items in preferences don't load anything

### ISSUE THREAD

**Issue by lchamp** [mpdifran/picasso-roadmap#57]
**Info:**
 Device: MacBook Air M1
 OS: Sonoma 14.3.1
 Picasso Version 1.3.1 (261)

**Describe the bug**
In the preferences sheet there are several actions/items that don't do anything and shows a white page.
This is the case, at least for me, for the following entries:

- Write a review
- Website
- Restore purchase
- Terms and conditions
- Privacy policy

**Screenshots**
<img width="498" alt="screenshot" src="https://github.com/mpdifran/picasso-roadmap/assets/6057771/f3089f0a-a72e-417a-8ce4-414f940774e4">

**Comment by mpdifran** [comment]
Ah I know what's going on here. I've used a bit of a hack to show the disclosure indicator where I set an empty navigation link in the background. If you click on that, it'll navigate to an empty screen. 

For now, you can work around this by clicking the content (app icon or text). I'll have this fixed ASAP!

**Comment by lchamp** [comment]
In case you are using something like this:
```
extension NavigationLink where Label == EmptyView, Destination == EmptyView {
   static var empty: NavigationLink {
       self.init(destination: EmptyView(), label: { EmptyView() })
   }
}
```
```
Button(action: {
    // your action / link
}) {
    HStack {
        Text("your associated text")
        Spacer()
        NavigationLink.empty
    }
    .contentShape(Rectangle()) // Workaround for the space to be tappable too
}
.buttonStyle(.plain)
```

Adding a contentShape can workaround the issue 👍

**Comment by mpdifran** [comment]
That's a great call, I'll try that!

**Comment by mpdifran** [comment]
Worked like a charm, the fix for this will be in the next version!
