### ISSUE TITLE
Save to filesystem broken

### ISSUE THREAD

**Issue by marcusisinger** [mpdifran/picasso-roadmap#64]
**Info:**
 Device: [e.g. iPhone 15 Pro]
 OS: [e.g. iOS 17.0.2]
 Picasso Version [e.g. 1.0]

**Describe the bug**
Export to file system gives access errors everywhere when trying to export. “You don’t have permission to save the file “en” to folder “Downloads” “ for example. 

**Expected behavior**
Should be able to save files.

**Comment by mpdifran** [comment]
So sorry about this! I've pushed a fix in version 1.4.2, please download that and let me know if you are still having issues!
